TFG/app/urls.py
from django.urls import path




from .views import *

urlpatterns = [


##---------- COMMONS --------------------------------------------------------------------------------------------

    path('', Landing.as_view(), name='landing'),
    path('home', Home.as_view(), name='home'),
    path('info/', InfoEstadoEquipoView.as_view(), name='info'),


    path('dashboard', DashboardAdmin.as_view(), name = 'dashboard'),
    path('dashboard_voice', DashboardAdminVoice.as_view(), name = 'dashboard_voice'),

#---------- REGISTRO --------------------------------------------------------------------------------------------
    path('registro/',UserRegister.as_view(), name='registro' ),

##---------- PERFIL --------------------------------------------------------------------------------------------
    path('perfil/', Perfil.as_view(), name='perfil'),
    path('update_profile',UserUpdateProfile.as_view(), name='update_profile'),
    path('perfil/eliminar/', EliminarCuentaView.as_view(), name='eliminar_cuenta'),

    
##---------- PARTIDOS --------------------------------------------------------------------------------------------
    path('crear_partidos/', CrearPartidos.as_view(), name='crear_partidos'),
    path('buscar_partidos/', BuscarPartidos.as_view(), name='buscar_partidos'),
    path('partido/<uuid:partido_id>/inscribirse/', InscribirsePartidoView.as_view(), name='inscribirse_partido'),
    path('partido/<uuid:pk>/', DetallePartidoView.as_view(), name='detalle_partido'),
    path('partido/<uuid:pk>/registrar_resultado/', RegistrarResultadoPartidoView.as_view(), name='registrar_resultado_partido'),

##---------- INSCRIPCIONES --------------------------------------------------------------------------------------------
path('partido/<uuid:pk>/<uuid:inscripcion_id>/aceptar/', AceptarInscripcionView.as_view(), name='aceptar_inscripcion'),
path('partido/<uuid:pk>/<uuid:inscripcion_id>/rechazar/', RechazarInscripcionView.as_view(), name='rechazar_inscripcion'),

##---------- INSCRIPCIONES (RETOS EQUIPO) --------------------------------------------------------------------------------------------

    path('partido/<uuid:pk>/solicitar_reto/', SolicitarUnirseRetoView.as_view(), name='solicitar_unirse_reto'),
    path('partido/<uuid:pk>/aceptar_reto/<uuid:inscripcion_id>/', AceptarRetoView.as_view(), name='aceptar_reto'),

##---------- CANCHAS --------------------------------------------------------------------------------------------
    path('canchas/', CanchasView.as_view(), name='canchas_lista'), 
    path('canchas/registrar/', RegistrarCanchaView.as_view(), name='canchas_registrar'),
    path('cancha/<uuid:pk_cancha>/', DetalleCanchaView.as_view(), name='detalle_cancha'),


##---------- EQUIPOS --------------------------------------------------------------------------------------------
    path('equipos/crear_equipo_permanente', CrearEquipoPermanenteView.as_view(), name='crear_equipo_permanente'),
    path('equipos/mis_equipos/', MisEquiposListView.as_view(), name='lista_mis_equipos'), 
    path('equipo/<uuid:pk>/', DetalleEquipoView.as_view(), name='detalle_equipo'), 
    path('equipo/<uuid:pk>/editar/', EditarEquipoPermanenteView.as_view(), name='editar_equipo_permanente'),
    path('equipo/<uuid:pk>/abandonar/', AbandonarEquipoView.as_view(), name='abandonar_equipo'),
    path('equipo/<uuid:pk>/eliminar/', EliminarEquipoView.as_view(), name='eliminar_equipo'),


##---------- MIS PARTIDOS --------------------------------------------------------------------------------------------

    path('mis_partidos/', MisPartidosView.as_view(), name='mis_partidos'),

##---------- ESTADISTICAS GENEREALES --------------------------------------------------------------------------------------------

    path('estadisticas/', EstadisticasView.as_view(), name='estadisticas_generales'),

# EQUIPOS----------------
    path('equipo/<uuid:pk>/gestionar-miembros/', GestionarMiembrosView.as_view(), name='gestionar_miembros'),
    
    
##---------- USUARIO / INVITACIONES --------------------------------------------------------------------------------------------

    path('mis-invitaciones/', MisInvitacionesView.as_view(), name='mis_invitaciones'),
    path('invitacion/<uuid:pk>/<str:accion>/', ResponderInvitacionView.as_view(), name='responder_invitacion'),

##----------------------TOGGLE ADMIN CAMBIAR ESTADO EQUIPO---------------------------------------------------------

    path('equipo/<uuid:pk>/toggle-activo/', ToggleActivoEquipoView.as_view(), name='toggle_activo_equipo'),





]

TFG/app/models/user.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.templatetags.static import static


class User(AbstractUser):
    TIPO_GENERO = [
        ('MASCULINO', 'Masculino'),
        ('FEMENINO', 'Femenino'),
        ('NO_ESPECIFICADO', 'Prefiero no decirlo'),
        ('OTRO', 'Otro'),
    ]

    TIPO_POSICION = [
        ('DELANTERO', 'Delantero'),
        ('CENTROCAMPISTA', 'Centrocampista'),
        ('DEFENSA', 'Defensa'),
        ('PORTERO', 'Portero')
    ]
    

    username = models.EmailField(max_length=150, unique=True, verbose_name="email", help_text="Introduce un email válido",)
    nombre = models.CharField(max_length=150)
    fecha_nacimiento = models.DateField(null=True, blank=True)

    genero = models.CharField(max_length=20, choices=TIPO_GENERO, default='NO_ESPECIFICADO', blank=True, null=True)
    
    posicion = models.CharField(max_length=50,choices=TIPO_POSICION, blank=True, null=True)
    partidos_jugados = models.IntegerField(default=0)
    victorias = models.IntegerField(default=0)
    derrotas = models.IntegerField(default=0)
    empates = models.IntegerField(default=0)
     
    calificacion = models.FloatField(default=1000.0)  # ELO

    imagen_perfil = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    banner_perfil = models.ImageField(upload_to='banner_perfil/', blank=True, null=True)
    ubicacion = models.CharField(max_length=255, blank=True, null=True)



    @property
    def get_avatar_url(self):
        """Devuelve la URL del avatar del usuario o la URL por defecto."""
        if self.imagen_perfil and hasattr(self.imagen_perfil, 'url'):
            return self.imagen_perfil.url
        return static('images/defaults/avatar_default.png')

    @property
    def get_banner_url(self):
        """Devuelve la URL del banner del perfil o la URL por defecto."""
        if self.banner_perfil and hasattr(self.banner_perfil, 'url'):
            return self.banner_perfil.url
        return static('images/defaults/banner_default.png')


    def __str__(self):
        return self.nombre
    
    def save(self, *args, **kwargs):
        #CASO DE QUE USUARIO CAMBIE DE EMAIL POR PERDIDA DE CONTRASEÑA
        if self.pk:  
            originalUser = User.objects.get(pk=self.pk)
            if originalUser.email != self.email:  # si cambia el email
                self.username = self.email  # actualizo el username

        super().save(*args, **kwargs)

TFG/app/views/equipo_views.py
from django.views.generic import CreateView,UpdateView, ListView, DetailView, View, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, LoginRequiredMixin, UserPassesTestMixin

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.db.models import Q
from app.forms.equipo_forms import EquipoCreateForm, EquipoUpdateForm, InvitarMiembroForm
from app.models.equipo import Equipo
from app.models.invitacion import InvitacionEquipo
from app.models.user import User
from django.views.generic.edit import FormMixin 

class CrearEquipoPermanenteView(LoginRequiredMixin, CreateView):
    model = Equipo
    form_class = EquipoCreateForm
    template_name = 'equipos/crear_equipo_permanente.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user # Pasar usuario al form para filtrar miembros_iniciales
        return kwargs

    def form_valid(self, form):
        # crea la instancia del equipo en memoria, pero NO en bbdd aún
        self.object = form.save(commit=False)
        
        self.object.capitan = self.request.user
        self.object.tipo_equipo = 'PERMANENTE'
        self.object.activo = True 

        # guarda el objeto Equipo principal en la base de datos.

        self.object.save()

        # guardar las relaciones ManyToMany 

        form.save_m2m()

        self.object.jugadores.add(self.request.user)
        
        messages.success(self.request, f"¡Equipo '{self.object.nombre_equipo}' creado con éxito!")
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('detalle_equipo', kwargs={'pk': self.object.id_equipo})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = "Crear Nuevo Equipo Permanente"
        return context

class MisEquiposListView(LoginRequiredMixin, ListView):
    model = Equipo
    template_name = 'equipos/mis_equipos_lista.html'
    context_object_name = 'equipos_list'
    paginate_by = 12

    def get_queryset(self):
        usuario = self.request.user
        
        # Si el usuario es un superusuario, TODOS los equipos
        if usuario.is_superuser:
            queryset = Equipo.objects.filter(
                tipo_equipo='PERMANENTE'
            ).distinct().order_by('-fecha_creacion')
        else:
            queryset = Equipo.objects.filter(
                tipo_equipo='PERMANENTE',
                activo=True 
            ).filter(
                Q(capitan=usuario) | Q(jugadores=usuario)
            ).distinct().order_by('-fecha_creacion')
            
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = "Mis Equipos"
        context['is_admin_view'] = self.request.user.is_superuser

        return context

class DetalleEquipoView(LoginRequiredMixin, DetailView):
    model = Equipo
    template_name = 'equipos/detalle_equipo.html'
    context_object_name = 'equipo'
    pk_url_kwarg = 'pk' # Coincide con <uuid:pk> en tu URL

    def get_queryset(self):
        usuario = self.request.user
        
        base_queryset = super().get_queryset().filter(tipo_equipo='PERMANENTE')

        if not usuario.is_superuser:
            return base_queryset.filter(activo=True)
        
        return base_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        equipo = self.get_object()
        context['titulo_pagina'] = f"Perfil del Equipo: {equipo.nombre_equipo}"
        context['es_capitan'] = (equipo.capitan == self.request.user)
        context['es_miembro'] = self.request.user in equipo.jugadores.all()

        context['is_admin_view'] = self.request.user.is_superuser
        
        return context

class EditarEquipoPermanenteView(LoginRequiredMixin, UpdateView):
    model = Equipo
    form_class = EquipoUpdateForm  
    template_name = 'equipos/editar_equipo_permanente.html'
    pk_url_kwarg = 'pk'

    def get_queryset(self):
        return super().get_queryset().filter(
            capitan=self.request.user, 
            tipo_equipo='PERMANENTE', 
            activo=True
        )
    

    def form_valid(self, form):
        messages.success(self.request, f"La información del equipo '{form.instance.nombre_equipo}' ha sido actualizada con éxito.")
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('detalle_equipo', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = f"Editar: {self.object.nombre_equipo}"
        context['equipo'] = self.object
        return context
    
class AbandonarEquipoView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        equipo = get_object_or_404(Equipo, pk=kwargs['pk'])
        usuario = request.user

        # es miembro del equipo?
        if not equipo.jugadores.filter(pk=usuario.pk).exists():
            messages.error(request, "No eres miembro de este equipo.")
            return redirect('detalle_equipo', pk=equipo.pk)

        # es capitán?
        if equipo.capitan == usuario:
            messages.error(request, "El capitán no puede abandonar el equipo. Debes eliminar el equipo o transferir la capitanía.")
            return redirect('detalle_equipo', pk=equipo.pk)

        # Eliminar al jugador del equipo
        equipo.jugadores.remove(usuario)
        
        messages.success(request, f"Has abandonado el equipo '{equipo.nombre_equipo}'.")
        return redirect('lista_mis_equipos')
    
class EliminarEquipoView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Equipo
    template_name = 'equipos/equipo_confirm_delete.html' 
    success_url = reverse_lazy('lista_mis_equipos') 
    context_object_name = 'equipo'

    def test_func(self):
        """Solo el capitán puede eliminar el equipo."""
        equipo = self.get_object()
        return equipo.capitan == self.request.user

    def form_valid(self, form):
        messages.success(self.request, f"El equipo '{self.object.nombre_equipo}' ha sido eliminado permanentemente.")
        return super().form_valid(form)

##---------------------------INVITACION------------------------------------------------------

class GestionarMiembrosView(LoginRequiredMixin, UserPassesTestMixin, FormMixin, DetailView):
    model = Equipo
    template_name = 'equipos/gestionar_miembros.html'
    context_object_name = 'equipo'
    pk_url_kwarg = 'pk'
    form_class = InvitarMiembroForm

    def test_func(self):
        """Asegura que solo el capitán pueda acceder."""
        equipo = self.get_object()
        return equipo.capitan == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        equipo = self.get_object()
        context['titulo_pagina'] = f"Gestionar: {equipo.nombre_equipo}"
        context['miembros'] = equipo.jugadores.all().order_by('nombre')
        context['invitaciones_pendientes'] = equipo.invitaciones.filter(estado='PENDIENTE')
        # El formulario se añade automáticamente por FormMixin
        return context

    def get_form_kwargs(self):
        """Pasa el equipo y el usuario actual al formulario."""
        kwargs = super().get_form_kwargs()
        kwargs['equipo'] = self.get_object()
        kwargs['invitador'] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        """Maneja las acciones POST (invitar o eliminar)."""
        self.object = self.get_object() # Necesario para FormMixin

        # --- Lógica para ELIMINAR un miembro ---
        if 'eliminar_miembro' in request.POST:
            miembro_id = request.POST.get('miembro_id')
            try:
                miembro_a_eliminar = self.object.jugadores.get(pk=miembro_id)
                if miembro_a_eliminar == self.object.capitan:
                    messages.error(request, "No puedes eliminar al capitán del equipo.")
                else:
                    self.object.jugadores.remove(miembro_a_eliminar)
                    messages.warning(request, f"{miembro_a_eliminar.nombre} ha sido eliminado del equipo.")
            except User.DoesNotExist:
                messages.error(request, "El miembro que intentas eliminar no existe.")
            return redirect('gestionar_miembros', pk=self.object.pk)

        # --- Lógica para INVITAR un miembro ---
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """Se ejecuta si el formulario de invitación es válido."""
        usuario_a_invitar = form.cleaned_data.get('email')
        
        InvitacionEquipo.objects.create(
            equipo=self.get_object(),
            invitado_por=self.request.user,
            invitado=usuario_a_invitar
        )
        
        messages.success(self.request, f"¡Invitación enviada a {usuario_a_invitar.nombre}!")
        return super().form_valid(form)

    def get_success_url(self):
        """Redirige a la misma página después de una acción exitosa."""
        return reverse('gestionar_miembros', kwargs={'pk': self.object.pk})
    
class ToggleActivoEquipoView(LoginRequiredMixin, UserPassesTestMixin, View):
    
    def test_func(self):
        return self.request.user.is_superuser

    def post(self, request, *args, **kwargs):
        equipo = get_object_or_404(Equipo, pk=kwargs['pk'])

        equipo.activo = not equipo.activo
        equipo.save(update_fields=['activo'])

        estado_str = "activado" if equipo.activo else "desactivado"

TFG/app/templates/equipos/gestionar_miembros.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ titulo_pagina|default:"Gestionar Miembros" }} - De Rabona{% endblock %}

{% block extra_css %}
    <style>
        /* ======= Variables y Base ======= */
        :root {
            --gestionar-primary: #f7835c;
            --gestionar-secondary: #00d4b1;
            --gestionar-bg-card: #1a1a2e;
            --gestionar-bg-elevated: #242438;
            --gestionar-border: rgba(255, 255, 255, 0.08);
            --gestionar-radius: 16px;
            --gestionar-radius-small: 12px;
            --gestionar-transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        /* ======= Animaciones ======= */
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .animate-in {
            opacity: 0;
            animation: fadeInUp 0.6s ease-out forwards;
        }

        /* ======= Estilos de la Página ======= */
        .page-header {
            animation: fadeInUp 0.5s ease-out;
        }

        .card {
            transition: var(--gestionar-transition);
        }
        .card:hover {
            transform: translateY(-4px);
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
            border-color: var(--gestionar-border-strong);
        }

        .card-header {
            background-color: var(--gestionar-bg-elevated) !important;
            border-bottom-color: var(--gestionar-border) !important;
        }
        .card-header h4 {
            color: var(--text-primary);
            font-size: 1.1rem;
            font-weight: 600;
        }
        .card-header i {
            color: var(--gestionar-primary);
        }

        /* ======= Lista de Miembros ======= */
        .list-group-item {
            transition: background-color 0.2s ease-in-out;
            border-bottom: 1px solid var(--gestionar-border) !important;
        }
        .list-group-item:last-child {
            border-bottom: none !important;
        }
        .list-group-item:hover {
            background-color: rgba(255, 255, 255, 0.04) !important;
        }

        .player-avatar {
            width: 48px;
            height: 48px;
            object-fit: cover;
            border: 2px solid var(--gestionar-border);
        }

        .player-name {
            font-weight: 600;
            color: var(--text-primary);
        }

        .captain-badge {
            font-size: 0.7rem;
            padding: 0.3em 0.7em;
            font-weight: 700;
            letter-spacing: 0.5px;
            background-color: var(--gestionar-primary) !important;
            color: white !important;
        }

        .btn-delete-member {
            background: rgba(239, 68, 68, 0.1);
            color: #ef4444;
            border: 1px solid rgba(239, 68, 68, 0.2);
            transition: var(--gestionar-transition);
        }
        .btn-delete-member:hover {
            background: #ef4444;
            color: white;
            transform: scale(1.1);
        }

        /* ======= Formulario de Invitación ======= */
        .invitation-form .form-label {
            font-weight: 500;
            color: var(--text-secondary);
        }
        .invitation-form .form-control {
            background-color: var(--gestionar-bg-elevated);
            border-color: var(--gestionar-border);
            color: var(--text-primary);
        }
        .invitation-form .form-control:focus {
            background-color: var(--gestionar-bg-elevated);
            border-color: var(--gestionar-primary);
            box-shadow: 0 0 0 3px rgba(247, 131, 92, 0.15);
            color: var(--text-primary);
        }
        .invitation-form .btn-success {
            background-color: var(--gestionar-secondary);
            border-color: var(--gestionar-secondary);
            font-weight: 600;
        }
        .invitation-form .btn-success:hover {
            background-color: #00c2a3;
            border-color: #00c2a3;
        }

        /* ======= Invitaciones Pendientes ======= */
        .pending-invitation-item {
            padding: 0.75rem 0;
            border-bottom: 1px solid var(--gestionar-border);
        }
        .pending-invitation-item:last-child {
            border-bottom: none;
        }
        .pending-avatar {
            width: 32px;
            height: 32px;
            object-fit: cover;
        }
        .pending-name {
            font-size: 0.9rem;
        }

        /* ======= Estado Vacío ======= */
        .empty-state {
            text-align: center;
            padding: 2rem 1rem;
            color: var(--text-muted);
        }
        .empty-state i {
            font-size: 2rem;
            margin-bottom: 1rem;
            display: block;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            
            <!-- Encabezado -->
            <div class="text-center mb-5 page-header">
                <h1 class="display-5 fw-bold">{{ titulo_pagina }}</h1>
                <p class="text-muted fs-5">Añade o elimina jugadores de la plantilla de <strong>{{ equipo.nombre_equipo }}</strong>.</p>
                <a href="{% url 'detalle_equipo' pk=equipo.pk %}" class="btn btn-sm btn-outline-secondary mt-2">
                    <i class="fas fa-arrow-left me-2"></i>Volver al Equipo
                </a>
            </div>

            <!-- Mensajes del Sistema -->
            {% if messages %}
                <div class="messages-section mb-4">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="row g-4">
                <!-- Columna de la Lista de Miembros -->
                <div class="col-md-7">
                    <div class="card bg-dark text-white border-secondary shadow-sm h-100 animate-in" style="animation-delay: 100ms;">
                        <div class="card-header">
                            <h4 class="mb-0"><i class="fas fa-users me-2"></i>Miembros Actuales ({{ miembros.count }})</h4>
                        </div>
                        <div class="card-body">
                            {% if miembros %}
                                <ul class="list-group list-group-flush">
                                    {% for miembro in miembros %}
                                        <li class="list-group-item bg-transparent text-white d-flex justify-content-between align-items-center px-0 py-3">
                                            <div class="d-flex align-items-center">
                                                <img src="{{ miembro.get_avatar_url }}" alt="Avatar de {{ miembro.nombre }}" class="rounded-circle me-3 player-avatar">
                                                <div>
                                                    <strong class="d-block player-name">{{ miembro.nombre }}</strong>
                                                    {% if miembro == equipo.capitan %}
                                                        <span class="badge captain-badge">Capitán</span>
                                                    {% else %}
                                                        <small class="text-muted">{{ miembro.get_posicion_display|default:"Jugador" }}</small>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            
                                            {% if miembro != equipo.capitan %}
                                                <form method="post" onsubmit="return confirm('¿Estás seguro de que quieres eliminar a {{ miembro.nombre }} del equipo?');">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="miembro_id" value="{{ miembro.pk }}">
                                                    <button type="submit" name="eliminar_miembro" class="btn btn-sm btn-delete-member" title="Eliminar del equipo">
                                                        <i class="fas fa-user-times"></i>
                                                    </button>
                                                </form>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <div class="empty-state">
                                    <i class="fas fa-user-friends"></i>
                                    <p>Aún no hay miembros en el equipo.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <!-- Columna para Invitar Miembros y Ver Pendientes -->
                <div class="col-md-5">
                    <!-- Formulario para Invitar -->
                    <div class="card bg-dark text-white border-secondary shadow-sm mb-4 animate-in" style="animation-delay: 200ms;">
                        <div class="card-header">
                            <h4 class="mb-0"><i class="fas fa-paper-plane me-2"></i>Invitar Nuevo Miembro</h4>
                        </div>
                        <div class="card-body">
                            <form method="post" class="invitation-form">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <div class="d-grid mt-3">
                                    <button type="submit" name="invitar_miembro" class="btn btn-success">
                                        <i class="fas fa-plus-circle me-2"></i>Enviar Invitación
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Lista de Invitaciones Pendientes -->
                    <div class="card bg-dark text-white border-secondary shadow-sm animate-in" style="animation-delay: 300ms;">
                        <div class="card-header">
                            <h4 class="mb-0"><i class="fas fa-clock me-2"></i>Invitaciones Pendientes</h4>
                        </div>
                        <div class="card-body">
                            {% if invitaciones_pendientes %}
                                <ul class="list-group list-group-flush">
                                    {% for invitacion in invitaciones_pendientes %}
                                        <li class="list-group-item bg-transparent text-white d-flex align-items-center px-0 py-2 pending-invitation-item">
                                            <img src="{{ invitacion.invitado.get_avatar_url }}" alt="Avatar" class="rounded-circle me-3 pending-avatar">
                                            <span class="pending-name">A <strong>{{ invitacion.invitado.nombre }}</strong></span>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <div class="empty-state">
                                    <i class="fas fa-envelope-open"></i>
                                    <p>No hay invitaciones pendientes.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}